### PR TITLE
Prefix Banner option and JSON output option

### PR DESCRIPTION
**Pull request by git-j**
when i used your project i stepped on this more than twice, liked your documentation and created my own workaround but wanted to contribute my expectations so i added the code in the right place.

### CODE REVIEW

**Comment by mdvanes** [comment]
Thanks for your contribution! I will look into it asap.

**Comment by mdvanes** [comment]
- I would replace my banner function by your banner_prefix
- I would rename as_json to asJson. Also the use of this feature is not very clear and it might belong better in a separate module
- there is a typo ("a object") in the documentation that I will fix
- I need to dive into the broken peer dependencies and license errors. Maybe this is because of the updates to Grunt.

**Comment by git-j** [comment]
the asJson is useful when you want to generate bookmarklets for 
different users in a webapp:

$.get('/bookmarklet.template.json').done(function(bookmarklet){
   var custom_bookmarklet = bookmarklet.href.replace(/USERNAME/, 
cookie.username);
   $('#bookmarklet_button').attr('href', custom_bookmarklet);
});

using the plain string with $.get is not as convienient (eg additional 
checks required if the data from get() is actually a singleline 
bookmarklet string).

currently i create the json using grunt-concat that breaks when newlines 
(from banner) are introduced.

**Comment by mdvanes** [comment]
Thanks for the clarification. I understand your usecase, but I don't think it should be part of the core of the bookmarklet-wrapper, since it is in turn a wrapper to JSON, which could take any kind of value as its key/values.

I will merge the full PR now, but I will remove this feature in the future. I do suggest to create a new separate module to perform this action. If you want help, I will be happy to take a look at it.

Concerning the grunt-concat problem with linebreaks: it should be possible to chain [grunt-replace](https://github.com/outatime/grunt-replace) with grunt-concat to first clean up the linebreaks.

**Comment by mdvanes** [comment]
Merged in version 1.2.0. The feature AsJson will be removed in 1.3.0.

**Pull request merged**
